@host=http://localhost:5023
GET  {{host}}/dinners
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI4NWIzOWE5Ni0xNTQwLTRkZDUtOTE5Zi05MTMxZGVlZTg1OTAiLCJnaXZlbl9uYW1lIjoiRmlkYW4iLCJmYW1pbHlfbmFtZSI6IkltYW5vdmEiLCJqdGkiOiJhN2M5ZTA0ZS0yNmQyLTQyMGUtYmI5Ni0wYzhjNjE2OWM0OWUiLCJleHAiOjE2NzE5MTQ2MjYsImlzcyI6IkJ1YmVyRGlubmVyIiwiYXVkIjoiQnViZXJEaW5uZXIifQ.Xq1kINLy4AmInV5CfArPX0Oq3GnUU_GT6Z9Ih5JpkgY